export const LIFESTYLE_CATEGORIES = [
  "Accessories",
  "Active Life",
  "Adult Education",
  "Adult Entertainment",
  "Air",
  "Amusement Parks",
  "Appliances",
  "Appliances & Repair",
  "Arcades",
  "Arabic",
  "Armenian",
  "Art Galleries",
  "Arts & Crafts",
  "Arts & Entertainment",
  "Auto",
  "Auto Detailing",
  "Auto Glass Services",
  "Auto Repair",
  "Automotive",
  "Banks",
  "Banks & Credit Unions",
  "Bar",
  "Bar Crawl",
  "Barbers",
  "Barista",
  "Bars",
  "Bartenders",
  "Battery",
  "Battery Stores",
  "Batting Cages",
  "Beaches",
  "Beauty & Spas",
  "Bed & Breakfast",
  "Beer",
  "Beer Bar",
  "Beer Gardens",
  "Beer Hall",
  "Beer Tours",
  "Boating",
  "Boat",
  "Boat Charters",
  "Boat Tours",
  "Body Shops",
  "Books",
  "Bookstores",
  "Bowling",
  "Business",
  "Business Consulting",
  "Cabaret",
  "Cafes",
  "Cafeteria",
  "Cannabis Dispensaries",
  "Car",
  "Car Dealers",
  "Car Stereo Installation",
  "Cards & Stationery",
  "Casinos",
  "Child Care & Day Care",
  "Children",
  "Children's Clothing",
  "Chiropractors",
  "Chocolatiers & Shops",
  "Christmas Trees",
  "Churches",
  "Cinema",
  "Cleaning",
  "Clubs",
  "Cocktail Bars",
  "Comedy",
  "Comedy Clubs",
  "Community Service/Non-Profit",
  "Computer",
  "Conditioning",
  "Convenience Stores",
  "Cosmetics",
  "Cosmetics & Beauty Supply",
  "Counseling & Mental Health",
  "Country",
  "Country Clubs",
  "Crane",
  "Crane Services",
  "Crafts",
  "Dance Clubs",
  "Day Spas",
  "Department Stores",
  "Departments of Motor Vehicles",
  "Doctors",
  "Dog Parks",
  "Drugstores",
  "Dry Cleaning & Laundry",
  "Education",
  "Educational",
  "Educational Services",
  "Electronics",
  "Electronics Repair",
  "Entertainment",
  "Equipment",
  "Event Planning & Services",
  "Events",
  "Eyewear & Opticians",
  "Fashion",
  "Festivals",
  "Financial",
  "Financial Services",
  "Fireworks",
  "Fishing",
  "Fitness & Instruction",
  "Florists",
  "Flowers",
  "Flowers & Gifts",
  "Food Stands",
  "Funeral",
  "Funeral Services & Cemeteries",
  "Furniture",
  "Furniture Stores",
  "Galleries",
  "Gas",
  "Gas Stations",
  "Gastropubs",
  "Gear",
  "Gifts",
  "Go Karts",
  "Golf",
  "Golf Equipment",
  "Golf Lessons",
  "Gun",
  "Gun/Rifle Ranges",
  "Guns & Ammo",
  "Hair",
  "Hair Removal",
  "Hair Salons",
  "Hardware",
  "Hardware Stores",
  "Health",
  "Health & Medical",
  "Health Markets",
  "Heating",
  "Heating & Air Conditioning/HVAC",
  "Herbal",
  "Herbal Shops",
  "Home & Garden",
  "Home Cleaning",
  "Home Decor",
  "Home Services",
  "Hotels",
  "Hotels & Travel",
  "HVAC",
  "Indoor",
  "Indoor Playcentre",
  "Internet Cafes",
  "Irish Pub",
  "IT",
  "IT Services & Computer Repair",
  "Jazz & Blues",
  "Jewelry",
  "Junk Removal & Hauling",
  "Kids Activities",
  "Kitchen & Bath",
  "Kitchen Supplies",
  "Laser",
  "Laser Tag",
  "Leisure Centers",
  "Lessons",
  "Life",
  "Local Flavor",
  "Local Services",
  "Lounges",
  "Mags",
  "Massage",
  "Maternity Wear",
  "Mental",
  "Mini Golf",
  "Motor",
  "Motorcycle Dealers",
  "Motorcycles",
  "Movies (Cinema)",
  "Museum",
  "Museums",
  "Music",
  "Music & DVDs",
  "Music & Video",
  "Music Venues",
  "Musicians",
  "Nail",
  "Nail Salons",
  "Nightlife",
  "Nurseries & Gardening",
  "Outdoor",
  "Outdoor Gear",
  "Parking",
  "Parks",
  "Party & Event Planning",
  "Party Equipment Rentals",
  "Party Supplies",
  "Performing Arts",
  "Personal Shopping",
  "Pet Adoption",
  "Pet Services",
  "Pet Sitting",
  "Pet Stores",
  "Pets",
  "Playcenter",
  "Playgrounds",
  "Pool",
  "Pool & Billiards",
  "Pool Halls",
  "Preschools",
  "Professional Services",
  "Public Markets",
  "Public Services & Government",
  "Pub",
  "Pubs",
  "Race",
  "Race Tracks",
  "Religious Organizations",
  "Repair",
  "Resorts",
  "Restaurants",
  "Roadside Assistance",
  "School",
  "Self Storage",
  "Service",
  "Shopping",
  "Shopping Centers",
  "Skating Rinks",
  "Skin Care",
  "Smog Check Stations",
  "Social Clubs",
  "Souvenir Shops",
  "Spas",
  "Sporting Goods",
  "Sports Bars",
  "Sports Clubs",
  "Sports Wear",
  "Stationery",
  "Strip Clubs",
  "Swimming Pools",
  "Tag",
  "Tapas Bars",
  "Tennis",
  "Themed Cafes",
  "Thrift Stores",
  "Tiki Bars",
  "Tires",
  "Tobacco Shops",
  "Tours",
  "Tracks",
  "Trailer Repair",
  "Transmission Repair",
  "Transportation",
  "Travel Services",
  "Used Bookstore",
  "Venues & Event Spaces",
  "Vehicles",
  "Vitamins & Supplements",
  "Waxing",
  "Wedding Planning",
  "Wholesale Stores",
  "Windshield Installation & Repair",
  "Wine & Spirits",
  "Wine Bars",
  "Wine Tasting Classes",
  "Wine Tasting Room",
  "Wineries",
  "Women's Clothing",
  "Wear",
  "Yelp Events",
  "Yoga",
];

export const FOOD_CATEGORIES = [
  "Acai Bowls",
  "Afghan",
  "African",
  "American (New)",
  "American (Traditional)",
  "Arabic",
  "Argentine",
  "Asian Fusion",
  "Austrian",
  "Bagels",
  "Bakeries",
  "Bar",
  "Barbeque",
  "Beer",
  "Beverage Store",
  "Bistros",
  "Brasseries",
  "Brazilian",
  "Breakfast & Brunch",
  "Breweries",
  "British",
  "Bubble Tea",
  "Buffets",
  "Burgers",
  "Burmese",
  "Butcher",
  "Cafes",
  "Cafeteria",
  "Cajun/Creole",
  "Cambodian",
  "Canadian (New)",
  "Candy Stores",
  "Cantonese",
  "Caterers",
  "Cheese Shops",
  "Cheesesteaks",
  "Chicken Shop",
  "Chicken Wings",
  "Chinese",
  "Chocolatiers & Shops",
  "Cideries",
  "Coffee & Tea",
  "Coffee Roasteries",
  "Colombian",
  "Comfort Food",
  "Convenience Stores",
  "Creperies",
  "Cuban",
  "Cupcakes",
  "Custom Cakes",
  "Delicatessen",
  "Delis",
  "Desserts",
  "Dim Sum",
  "Diners",
  "Distilleries",
  "Do-It-Yourself Food",
  "Donuts",
  "Empanadas",
  "Ethiopian",
  "Ethnic Food",
  "Falafel",
  "Farmers Market",
  "Fast Food",
  "Filipino",
  "Fish & Chips",
  "Fondue",
  "Food",
  "Food Court",
  "Food Delivery Services",
  "Food Stands",
  "Food Trucks",
  "French",
  "Fruits & Veggies",
  "Gelato",
  "German",
  "Gluten-Free",
  "Greek",
  "Grocery",
  "Hainan",
  "Halal",
  "Hawaiian",
  "Herbs & Spices",
  "Himalayan/Nepalese",
  "Hong Kong Style Cafe",
  "Hot Dogs",
  "Hot Pot",
  "Ice Cream & Frozen Yogurt",
  "Imported Food",
  "Indian",
  "Indonesian",
  "International",
  "International Grocery",
  "Irish",
  "Italian",
  "Japanese",
  "Japanese Curry",
  "Juice Bars & Smoothies",
  "Kebab",
  "Korean",
  "Kosher",
  "Laotian",
  "Latin American",
  "Lebanese",
  "Live/Raw Food",
  "Local Flavor",
  "Malaysian",
  "Meat Shops",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Modern European",
  "Mongolian",
  "Moroccan",
  "New Mexican Cuisine",
  "Noodles",
  "Organic Stores",
  "Oriental",
  "Pakistani",
  "Pan Asian",
  "Pancakes",
  "Pasta Shops",
  "Patisserie/Cake Shop",
  "Persian/Iranian",
  "Personal Chefs",
  "Peruvian",
  "Pizza",
  "Poke",
  "Polish",
  "Pop-Up Restaurants",
  "Portuguese",
  "Poutineries",
  "Pretzels",
  "Ramen",
  "Restaurants",
  "Salad",
  "Salvadoran",
  "Sandwiches",
  "Sardinian",
  "Seafood",
  "Seafood Markets",
  "Senegalese",
  "Shanghainese",
  "Shaved Ice",
  "Shaved Snow",
  "Sicilian",
  "Singaporean",
  "Smokehouse",
  "Somali",
  "Soul Food",
  "Soup",
  "Southern",
  "Spanish",
  "Specialty Food",
  "Steakhouses",
  "Street Vendors",
  "Sushi Bars",
  "Syrian",
  "Szechuan",
  "Tacos",
  "Taiwanese",
  "Tapas Bars",
  "Tapas/Small Plates",
  "Tea Rooms",
  "Teppanyaki",
  "Tex-Mex",
  "Thai",
  "Themed Cafes",
  "Turkish",
  "Tuscan",
  "Ukrainian",
  "Vegan",
  "Vegetarian",
  "Venezuelan",
  "Vietnamese",
  "Waffles",
  "Wine & Spirits",
  "Wraps",
];

const CATEGORY_ICON_RULES = [
  { keywords: ["szchuan", "sichuan", "china", "chinese"], icon: "🇨🇳" },
  { keywords: ["japan", "japanese"], icon: "🇯🇵" },
  { keywords: ["korea", "korean"], icon: "🇰🇷" },
  { keywords: ["thai", "thailand"], icon: "🇹🇭" },
  { keywords: ["india", "indian"], icon: "🇮🇳" },
  { keywords: ["vietnam", "vietnamese"], icon: "🇻🇳" },
  { keywords: ["philippines", "filipino"], icon: "🇵🇭" },
  { keywords: ["indonesia", "indonesian"], icon: "🇮🇩" },
  { keywords: ["malaysia", "malaysian"], icon: "🇲🇾" },
  { keywords: ["singapore", "singaporean"], icon: "🇸🇬" },
  { keywords: ["italy", "italian"], icon: "🇮🇹" },
  { keywords: ["france", "french"], icon: "🇫🇷" },
  { keywords: ["greece", "greek"], icon: "🇬🇷" },
  { keywords: ["spain", "spanish"], icon: "🇪🇸" },
  { keywords: ["mexico", "mexican"], icon: "🇲🇽" },
  { keywords: ["canada", "canadian"], icon: "🇨🇦" },
  { keywords: ["america", "american", "usa", "u.s."], icon: "🇺🇸" },
  { keywords: ["brazil", "brazilian"], icon: "🇧🇷" },
  { keywords: ["argentina", "argentinian"], icon: "🇦🇷" },
  { keywords: ["peru", "peruvian"], icon: "🇵🇪" },
  { keywords: ["colombia", "colombian"], icon: "🇨🇴" },
  { keywords: ["venezuela", "venezuelan"], icon: "🇻🇪" },
  { keywords: ["cuba", "cuban"], icon: "🇨🇺" },
  { keywords: ["jamaica", "jamaican"], icon: "🇯🇲" },
  { keywords: ["turkey", "turkish"], icon: "🇹🇷" },
  { keywords: ["lebanon", "lebanese"], icon: "🇱🇧" },
  { keywords: ["morocco", "moroccan"], icon: "🇲🇦" },
  { keywords: ["ethiopia", "ethiopian"], icon: "🇪🇹" },
  { keywords: ["russia", "russian"], icon: "🇷🇺" },
  { keywords: ["germany", "german"], icon: "🇩🇪" },
  { keywords: ["ireland", "irish"], icon: "🇮🇪" },
  { keywords: ["england", "english", "british", "uk", "u.k."], icon: "🇬🇧" },
  { keywords: ["australia", "australian"], icon: "🇦🇺" },
  { keywords: ["afghanistan", "afghan"], icon: "🇦🇫" },
  { keywords: ["pakistan", "pakistani"], icon: "🇵🇰" },
  { keywords: ["bangladesh", "bangladeshi"], icon: "🇧🇩" },
  { keywords: ["nepal", "nepalese"], icon: "🇳🇵" },
  { keywords: ["asian fusion"], icon: "🍣" },
  { keywords: ["sushi"], icon: "🍣" },
  { keywords: ["beverage store", "beverage"], icon: "🥤" },
  { keywords: ["hot dog", "hot dogs"], icon: "🌭" },
  { keywords: ["butcher", "butcher shop"], icon: "🥩" },
  { keywords: ["pizza"], icon: "🍕" },
  { keywords: ["burger", "cheesesteak"], icon: "🍔" },
  { keywords: ["taco", "tex-mex", "mexican"], icon: "🌮" },
  { keywords: ["bbq", "barbeque", "barbecue", "smokehouse"], icon: "🍖" },
  { keywords: ["chicken"], icon: "🍗" },
  { keywords: ["steak"], icon: "🥩" },
  { keywords: ["seafood", "fish", "oyster"], icon: "🐟" },
  { keywords: ["ramen", "noodle", "noodles", "pho", "soup"], icon: "🍜" },
  { keywords: ["salad", "vegan", "vegetarian"], icon: "🥗" },
  { keywords: ["sandwich", "sub", "wrap"], icon: "🥪" },
  { keywords: ["breakfast", "brunch", "pancake", "waffle"], icon: "🥞" },
  { keywords: ["coffee", "cafe", "cafes", "tea"], icon: "☕" },
  {
    keywords: ["dessert", "ice cream", "gelato", "donut", "donuts", "shaved ice"],
    icon: "🍨",
  },
  { keywords: ["bakery", "bakeries", "bread", "pastry", "cake", "cupcake"], icon: "🥐" },
  { keywords: ["bar", "pub", "lounge", "nightlife", "tapas"], icon: "🍸" },
  { keywords: ["beer", "brewery", "cider", "wine", "spirits"], icon: "🍺" },
  { keywords: ["deli", "delicatessen", "cheese"], icon: "🧀" },
  { keywords: ["market", "grocery"], icon: "🛒" },
  { keywords: ["food truck", "food trucks", "street vendors"], icon: "🚚" },
  { keywords: ["french"], icon: "🥖" },
  { keywords: ["thai", "curry", "indian"], icon: "🍛" },
  { keywords: ["italian", "pasta"], icon: "🍝" },
  { keywords: ["korean", "teppanyaki"], icon: "🥢" },
  { keywords: ["mediterranean", "greek"], icon: "🫒" },
];

const CATEGORY_SUFFIXES = new Set([
  "restaurant",
  "restaurants",
  "bar",
  "bars",
  "cafe",
  "cafes",
  "pub",
  "pubs",
]);

const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const MAIN_CATEGORY_RULES = [
  {
    label: "Burgers",
    keywords: ["burger", "burgers", "hamburger", "cheeseburger","barbecue_restaurant","hamburger_restaurant","fast_food_restaurant","Chicken Shop","Chicken Wings"],
  },
   {
    label: "Ice Cream & Frozen Yogurt",
    keywords: ["burger", "burgers", "hamburger", "cheeseburger","Ice Cream & Frozen Yogurt","Gelat","fast_food_restaurant","Donuts","Breakfast & Brunch"],
  },
   {
    label: "Acai Bowls",
    keywords: ["Ice Cream & Frozen Yogurt","Gelat","fast_food_restaurant","Donuts","Breakfast & Brunch"],
  },
   {
    label: "Donuts",
    keywords: ["Donuts","Desserts","Chocolatiers & Shops","Breakfast & Brunch","Bubble Tea", "tea", "Coffee & Tea"],
  },
  {
    label: "Bakeries",
    keywords: ["Donuts","Desserts","Chocolatiers & Shops","Breakfast & Brunch","Bubble Tea", "tea", "Coffee & Tea"],
  },
  {
    label: "Breakfast & Brunch",
    keywords: ["Donuts","Desserts","Chocolatiers & Shops","Breakfast & Brunch","Waffles","Bubble Tea", "tea", "Coffee & Tea", "Coffee Roasteries"],
  },
  {
    label: "Cafe",
    keywords: ["Bubble Tea", "tea", "Coffee & Tea", "Coffee Roasteries","Colombian","Breakfast & Brunch", "Hong Kong Style Cafe","cafes","cafeteria","Point Of Interest","fast_food_restaurant","Fast Food","Candy Store"],
  },
  {
    label: "American (New)",
    keywords: ["american (new)", "new american", "modern american","barbecue_restaurant","american_restaurant","fast_food_restaurant","Chicken Shop","Chicken Wings"],
  },
  {
    label: "American (Traditional)",
    keywords: ["american (traditional)", "traditional american", "Breakfast & Brunch", "classic american","barbecue_restaurant","american_restaurant","fast_food_restaurant","Chicken Shop","Chicken Wings"],
  },
   {
    label: "Breakfast & Brunch",
    keywords: ["Bubble Tea", "Donuts","Desserts","Chocolatiers & Shops","tea", "Coffee & Tea", "Coffee Roasteries","Colombian","american (traditional)", "traditional american", "Breakfast & Brunch", "classic american","barbecue_restaurant","american_restaurant","fast_food_restaurant","Chicken Shop","Chicken Wings"],
  },
  {
    label: "Beer",
    keywords: ["Beer", "Beverage Store", "Brazilian", "breweries", "Spanish","bar","wine_bar","Night Club"],
  },
  {
    label: "Barbeque",
    keywords: ["barbeque", "barbecue", "bbq", "smokehouse","barbecue_restaurant","bar_and_grill","Chicken Shop","Chicken Wings","Hot Dogs"],
  },
   {
    label: "Butcher",
    keywords: ["barbeque", "barbecue", "bbq", "smokehouse","barbecue_restaurant","bar_and_grill","Chicken Shop","Chicken Wings","Hot Dogs"],
  },
  {
    label: "Custom Cakes",
    keywords: ["Donuts","Desserts","Chocolatiers & Shops","Breakfast & Brunch","Waffles","Bubble Tea", "tea", "Coffee & Tea", "Coffee Roasteries"],
  },
   {
    label: "Hot Dogs",
    keywords: ["barbeque", "barbecue", "bbq", "smokehouse","barbecue_restaurant","bar_and_grill","Chicken Shop","Chicken Wings","Hot Dogs"],
  },
  {
    label:"Beverage Store"
    keywords: ["Beer", "beer bar", "brewery", "breweries", "brewpub","bar","wine_bar","night_club","store"],
  },
  {
    label:"Pizza"
    keywords: ["italian_restaurant", "restaurant", "food", "breweries", "brewpub","bar","wine_bar","night_club","store","pizza_restaurant"],
       },
   {
    label:"Italian"
    keywords: ["italian_restaurant", "restaurant", "food", "breweries", "brewpub","bar","wine_bar","night_club","store","pizza_restaurant","Chicken Shop","Chicken Wings"],
       },
   {
    label:"Japanese"
    keywords: ["japanese_restaurant", "restaurant", "food", "breweries", "brewpub","bar","wine_bar","night_club","store","sushi_restaurant","Sushi","Japanese","Point Of Interest"],
       },
     {
    label:"Spanish"
    keywords: ["spanish_restaurant", "restaurant", "food", "breweries", "brewpub","bar","wine_bar","night_club","store","pizza_restaurant","Point Of Interest","Chicken Shop","Chicken Wings"],
       },
];

const MAIN_CATEGORY_REGEX_RULES = MAIN_CATEGORY_RULES.map((rule) => ({
  label: rule.label,
  patterns: rule.keywords.map(
    (keyword) => new RegExp(`\\b${escapeRegExp(keyword)}\\b`, "i")
  ),
}));

const normalizeCategoryByKeyword = (value) => {
  const normalized = String(value).toLowerCase();
  for (const rule of MAIN_CATEGORY_REGEX_RULES) {
    if (rule.patterns.some((pattern) => pattern.test(normalized))) {
      return rule.label;
    }
  }
  return value;
};

const formatCategoryToken = (token) => {
  if (!token) return "";
  const trimmed = token.trim();
  if (!trimmed) return "";
  if (trimmed === trimmed.toUpperCase()) return trimmed;
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
};

export const normalizeCategoryLabel = (category = "") => {
  const raw = String(category).trim();
  if (!raw) return "";
  if (!raw.includes("_")) return normalizeCategoryByKeyword(raw);
  const tokens = raw
    .split("_")
    .map((item) => item.trim())
    .filter(Boolean);
  if (!tokens.length) return raw;
  const last = tokens[tokens.length - 1];
  if (last && CATEGORY_SUFFIXES.has(last.toLowerCase())) {
    tokens.pop();
  }
  if (!tokens.length) return raw;
  const formatted = tokens.map(formatCategoryToken).join(" ");
  return normalizeCategoryByKeyword(formatted);
};

export const getCategoryIcon = (category = "") => {
  const normalized = String(category).toLowerCase();
  for (const rule of CATEGORY_ICON_RULES) {
    if (rule.keywords.some((keyword) => normalized.includes(keyword))) {
      return rule.icon;
    }
  }
  return "🍽️";
};
