export const LIFESTYLE_CATEGORIES = [
  "Accessories",
  "Active Life",
  "Adult Education",
  "Adult Entertainment",
  "Air",
  "Amusement Parks",
  "Appliances",
  "Appliances & Repair",
  "Arcades",
  "Arabic",
  "Armenian",
  "Art Galleries",
  "Arts & Crafts",
  "Arts & Entertainment",
  "Auto",
  "Auto Detailing",
  "Auto Glass Services",
  "Auto Repair",
  "Automotive",
  "Banks",
  "Banks & Credit Unions",
  "Bar",
  "Bar Crawl",
  "Barbers",
  "Barista",
  "Bars",
  "Bartenders",
  "Battery",
  "Battery Stores",
  "Batting Cages",
  "Beaches",
  "Beauty & Spas",
  "Bed & Breakfast",
  "Beer",
  "Beer Bar",
  "Beer Gardens",
  "Beer Hall",
  "Beer Tours",
  "Boating",
  "Boat",
  "Boat Charters",
  "Boat Tours",
  "Body Shops",
  "Books",
  "Bookstores",
  "Bowling",
  "Business",
  "Business Consulting",
  "Cabaret",
  "Cafes",
  "Cafeteria",
  "Cannabis Dispensaries",
  "Car",
  "Car Dealers",
  "Car Stereo Installation",
  "Cards & Stationery",
  "Casinos",
  "Child Care & Day Care",
  "Children",
  "Children's Clothing",
  "Chiropractors",
  "Chocolatiers & Shops",
  "Christmas Trees",
  "Churches",
  "Cinema",
  "Cleaning",
  "Clubs",
  "Cocktail Bars",
  "Comedy",
  "Comedy Clubs",
  "Community Service/Non-Profit",
  "Computer",
  "Conditioning",
  "Convenience Stores",
  "Cosmetics",
  "Cosmetics & Beauty Supply",
  "Counseling & Mental Health",
  "Country",
  "Country Clubs",
  "Crane",
  "Crane Services",
  "Crafts",
  "Dance Clubs",
  "Day Spas",
  "Department Stores",
  "Departments of Motor Vehicles",
  "Doctors",
  "Dog Parks",
  "Drugstores",
  "Dry Cleaning & Laundry",
  "Education",
  "Educational",
  "Educational Services",
  "Electronics",
  "Electronics Repair",
  "Entertainment",
  "Equipment",
  "Event Planning & Services",
  "Events",
  "Eyewear & Opticians",
  "Fashion",
  "Festivals",
  "Financial",
  "Financial Services",
  "Fireworks",
  "Fishing",
  "Fitness & Instruction",
  "Florists",
  "Flowers",
  "Flowers & Gifts",
  "Food Stands",
  "Funeral",
  "Funeral Services & Cemeteries",
  "Furniture",
  "Furniture Stores",
  "Galleries",
  "Gas",
  "Gas Stations",
  "Gastropubs",
  "Gear",
  "Gifts",
  "Go Karts",
  "Golf",
  "Golf Equipment",
  "Golf Lessons",
  "Gun",
  "Gun/Rifle Ranges",
  "Guns & Ammo",
  "Hair",
  "Hair Removal",
  "Hair Salons",
  "Hardware",
  "Hardware Stores",
  "Health",
  "Health & Medical",
  "Health Markets",
  "Heating",
  "Heating & Air Conditioning/HVAC",
  "Herbal",
  "Herbal Shops",
  "Home & Garden",
  "Home Cleaning",
  "Home Decor",
  "Home Services",
  "Hotels",
  "Hotels & Travel",
  "HVAC",
  "Indoor",
  "Indoor Playcentre",
  "Internet Cafes",
  "Irish Pub",
  "IT",
  "IT Services & Computer Repair",
  "Jazz & Blues",
  "Jewelry",
  "Junk Removal & Hauling",
  "Kids Activities",
  "Kitchen & Bath",
  "Kitchen Supplies",
  "Laser",
  "Laser Tag",
  "Leisure Centers",
  "Lessons",
  "Life",
  "Local Flavor",
  "Local Services",
  "Lounges",
  "Mags",
  "Massage",
  "Maternity Wear",
  "Mental",
  "Mini Golf",
  "Motor",
  "Motorcycle Dealers",
  "Motorcycles",
  "Movies (Cinema)",
  "Museum",
  "Museums",
  "Music",
  "Music & DVDs",
  "Music & Video",
  "Music Venues",
  "Musicians",
  "Nail",
  "Nail Salons",
  "Nightlife",
  "Nurseries & Gardening",
  "Outdoor",
  "Outdoor Gear",
  "Parking",
  "Parks",
  "Party & Event Planning",
  "Party Equipment Rentals",
  "Party Supplies",
  "Performing Arts",
  "Personal Shopping",
  "Pet Adoption",
  "Pet Services",
  "Pet Sitting",
  "Pet Stores",
  "Pets",
  "Playcenter",
  "Playgrounds",
  "Pool",
  "Pool & Billiards",
  "Pool Halls",
  "Preschools",
  "Professional Services",
  "Public Markets",
  "Public Services & Government",
  "Pub",
  "Pubs",
  "Race",
  "Race Tracks",
  "Religious Organizations",
  "Repair",
  "Resorts",
  "Restaurants",
  "Roadside Assistance",
  "School",
  "Self Storage",
  "Service",
  "Shopping",
  "Shopping Centers",
  "Skating Rinks",
  "Skin Care",
  "Smog Check Stations",
  "Social Clubs",
  "Souvenir Shops",
  "Spas",
  "Sporting Goods",
  "Sports Bars",
  "Sports Clubs",
  "Sports Wear",
  "Stationery",
  "Strip Clubs",
  "Swimming Pools",
  "Tag",
  "Tapas Bars",
  "Tennis",
  "Themed Cafes",
  "Thrift Stores",
  "Tiki Bars",
  "Tires",
  "Tobacco Shops",
  "Tours",
  "Tracks",
  "Trailer Repair",
  "Transmission Repair",
  "Transportation",
  "Travel Services",
  "Used Bookstore",
  "Venues & Event Spaces",
  "Vehicles",
  "Vitamins & Supplements",
  "Waxing",
  "Wedding Planning",
  "Wholesale Stores",
  "Windshield Installation & Repair",
  "Wine & Spirits",
  "Wine Bars",
  "Wine Tasting Classes",
  "Wine Tasting Room",
  "Wineries",
  "Women's Clothing",
  "Wear",
  "Yelp Events",
  "Yoga",
];

export const FOOD_CATEGORIES = [
  "Acai Bowls",
  "Afghan",
  "African",
  "American (New)",
  "American (Traditional)",
  "Arabic",
  "Argentine",
  "Asian Fusion",
  "Austrian",
  "Bagels",
  "Bakeries",
  "Bar",
  "Barbeque",
  "Beer",
  "Beverage Store",
  "Bistros",
  "Brasseries",
  "Brazilian",
  "Breakfast & Brunch",
  "Breweries",
  "British",
  "Bubble Tea",
  "Buffets",
  "Burgers",
  "Burmese",
  "Butcher",
  "Cafes",
  "Cafeteria",
  "Cajun/Creole",
  "Cambodian",
  "Canadian (New)",
  "Candy Stores",
  "Cantonese",
  "Caterers",
  "Cheese Shops",
  "Cheesesteaks",
  "Chicken Shop",
  "Chicken Wings",
  "Chinese",
  "Chocolatiers & Shops",
  "Cideries",
  "Coffee & Tea",
  "Coffee Roasteries",
  "Colombian",
  "Comfort Food",
  "Convenience Stores",
  "Creperies",
  "Cuban",
  "Cupcakes",
  "Custom Cakes",
  "Delicatessen",
  "Delis",
  "Desserts",
  "Dim Sum",
  "Diners",
  "Distilleries",
  "Do-It-Yourself Food",
  "Donuts",
  "Empanadas",
  "Ethiopian",
  "Ethnic Food",
  "Falafel",
  "Farmers Market",
  "Fast Food",
  "Filipino",
  "Fish & Chips",
  "Fondue",
  "Food",
  "Food Court",
  "Food Delivery Services",
  "Food Stands",
  "Food Trucks",
  "French",
  "Fruits & Veggies",
  "Gelato",
  "German",
  "Gluten-Free",
  "Greek",
  "Grocery",
  "Hainan",
  "Halal",
  "Hawaiian",
  "Herbs & Spices",
  "Himalayan/Nepalese",
  "Hong Kong Style Cafe",
  "Hot Dogs",
  "Hot Pot",
  "Ice Cream & Frozen Yogurt",
  "Imported Food",
  "Indian",
  "Indonesian",
  "International",
  "International Grocery",
  "Irish",
  "Italian",
  "Japanese",
  "Japanese Curry",
  "Juice Bars & Smoothies",
  "Kebab",
  "Korean",
  "Kosher",
  "Laotian",
  "Latin American",
  "Lebanese",
  "Live/Raw Food",
  "Local Flavor",
  "Malaysian",
  "Meat Shops",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Modern European",
  "Mongolian",
  "Moroccan",
  "New Mexican Cuisine",
  "Noodles",
  "Organic Stores",
  "Oriental",
  "Pakistani",
  "Pan Asian",
  "Pancakes",
  "Pasta Shops",
  "Patisserie/Cake Shop",
  "Persian/Iranian",
  "Personal Chefs",
  "Peruvian",
  "Pizza",
  "Poke",
  "Polish",
  "Pop-Up Restaurants",
  "Portuguese",
  "Poutineries",
  "Pretzels",
  "Ramen",
  "Restaurants",
  "Salad",
  "Salvadoran",
  "Sandwiches",
  "Sardinian",
  "Seafood",
  "Seafood Markets",
  "Senegalese",
  "Shanghainese",
  "Shaved Ice",
  "Shaved Snow",
  "Sicilian",
  "Singaporean",
  "Smokehouse",
  "Somali",
  "Soul Food",
  "Soup",
  "Southern",
  "Spanish",
  "Specialty Food",
  "Steakhouses",
  "Street Vendors",
  "Sushi Bars",
  "Syrian",
  "Szechuan",
  "Tacos",
  "Taiwanese",
  "Tapas Bars",
  "Tapas/Small Plates",
  "Tea Rooms",
  "Teppanyaki",
  "Tex-Mex",
  "Thai",
  "Themed Cafes",
  "Turkish",
  "Tuscan",
  "Ukrainian",
  "Vegan",
  "Vegetarian",
  "Venezuelan",
  "Vietnamese",
  "Waffles",
  "Wine & Spirits",
  "Wraps",
];
